# Generated by Django 2.2.1 on 2019-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190520_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_data',
            new_name='list_date',
        ),
    ]
